name: flutter_gradients
description: A curated collection of awesome gradients made in Dart for Flutter.
version: 1.0.0+3

homepage: https://github.com/fluttercommunity/flutter_gradients
maintainer: Jonathan Monga (@JonathanMonga)

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
